CREATE LOCAL TEMPORARY COLUMN TABLE #CONFIGURE_LIBRARIES_PARAMETERS LIKE _SYS_DI.TT_PARAMETERS;
CREATE LOCAL TEMPORARY COLUMN TABLE #CONFIGURE_LIBRARIES_LIBRARY_CONFIGURATION LIKE _SYS_DI.TT_LIBRARY_CONFIGURATION;
INSERT INTO #CONFIGURE_LIBRARIES_LIBRARY_CONFIGURATION ( ACTION, LIBRARY_NAME ) VALUES ( 'ADD', 'com.sap.hana.di.sysbicsynonym' );
--CALL 0VCYOSC4ETZBHCC2_OPENSAP_HANA5_EXAMPLE#DI.CONFIGURE_LIBRARIES(#CONFIGURE_LIBRARIES_LIBRARY_CONFIGURATION, #CONFIGURE_LIBRARIES_PARAMETERS, ?, ?, ?); -- could also be called using group API, or _SYS_DI API

--CALL _SYS_DI.CONFIGURE_LIBRARIES('0VCYOSC4ETZBHCC2_OPENSAP_HANA5_EXAMPLE', #CONFIGURE_LIBRARIES_LIBRARY_CONFIGURATION, #CONFIGURE_LIBRARIES_PARAMETERS, ?, ?, ?);
CALL _SYS_DI.CONFIGURE_LIBRARIES((SELECT CURRENT_SCHEMA FROM DUMMY), #CONFIGURE_LIBRARIES_LIBRARY_CONFIGURATION, #CONFIGURE_LIBRARIES_PARAMETERS, ?, ?, ?);
DROP TABLE #CONFIGURE_LIBRARIES_PARAMETERS;
DROP TABLE #CONFIGURE_LIBRARIES_LIBRARY_CONFIGURATION;

